package com.xt.edu.mapper;


import java.util.List;

import com.xt.edu.model.Recommend;
import com.xt.edu.model.RecommendExample;
import org.apache.ibatis.annotations.Param;

public interface RecommendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recommend
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    long countByExample(RecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recommend
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    int deleteByExample(RecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recommend
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recommend
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    int insert(Recommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recommend
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    int insertSelective(Recommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recommend
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    List<Recommend> selectByExample(RecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recommend
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    Recommend selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recommend
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    int updateByExampleSelective(@Param("record") Recommend record, @Param("example") RecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recommend
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    int updateByExample(@Param("record") Recommend record, @Param("example") RecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recommend
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    int updateByPrimaryKeySelective(Recommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recommend
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    int updateByPrimaryKey(Recommend record);
}