package com.xt.edu.mapper;


import java.util.List;

import com.xt.edu.model.Salary;
import com.xt.edu.model.SalaryExample;
import org.apache.ibatis.annotations.Param;

public interface SalaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    long countByExample(SalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    int deleteByExample(SalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    int insert(Salary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    int insertSelective(Salary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    List<Salary> selectByExample(SalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    Salary selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    int updateByExampleSelective(@Param("record") Salary record, @Param("example") SalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    int updateByExample(@Param("record") Salary record, @Param("example") SalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    int updateByPrimaryKeySelective(Salary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    int updateByPrimaryKey(Salary record);
}