package com.xt.edu.mapper;


import com.xt.edu.model.Webcourse;
import com.xt.edu.model.WebcourseExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface WebcourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_webcourse
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    long countByExample(WebcourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_webcourse
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    int deleteByExample(WebcourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_webcourse
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_webcourse
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    int insert(Webcourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_webcourse
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    int insertSelective(Webcourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_webcourse
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    List<Webcourse> selectByExample(WebcourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_webcourse
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    Webcourse selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_webcourse
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    int updateByExampleSelective(@Param("record") Webcourse record, @Param("example") WebcourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_webcourse
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    int updateByExample(@Param("record") Webcourse record, @Param("example") WebcourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_webcourse
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    int updateByPrimaryKeySelective(Webcourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_webcourse
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    int updateByPrimaryKey(Webcourse record);
}