package com.xt.edu.model;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.id
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.name
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.type
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.company_name
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.company_address
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    private String companyAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.business_pic
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    private String businessPic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.company_lawer
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    private String companyLawer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.bank
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    private String bank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.bank_account
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    private String bankAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.phone
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.id
     *
     * @return the value of t_customer.id
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.id
     *
     * @param id the value for t_customer.id
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.name
     *
     * @return the value of t_customer.name
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.name
     *
     * @param name the value for t_customer.name
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.type
     *
     * @return the value of t_customer.type
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.type
     *
     * @param type the value for t_customer.type
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.company_name
     *
     * @return the value of t_customer.company_name
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.company_name
     *
     * @param companyName the value for t_customer.company_name
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.company_address
     *
     * @return the value of t_customer.company_address
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public String getCompanyAddress() {
        return companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.company_address
     *
     * @param companyAddress the value for t_customer.company_address
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public void setCompanyAddress(String companyAddress) {
        this.companyAddress = companyAddress == null ? null : companyAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.business_pic
     *
     * @return the value of t_customer.business_pic
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public String getBusinessPic() {
        return businessPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.business_pic
     *
     * @param businessPic the value for t_customer.business_pic
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public void setBusinessPic(String businessPic) {
        this.businessPic = businessPic == null ? null : businessPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.company_lawer
     *
     * @return the value of t_customer.company_lawer
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public String getCompanyLawer() {
        return companyLawer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.company_lawer
     *
     * @param companyLawer the value for t_customer.company_lawer
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public void setCompanyLawer(String companyLawer) {
        this.companyLawer = companyLawer == null ? null : companyLawer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.bank
     *
     * @return the value of t_customer.bank
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.bank
     *
     * @param bank the value for t_customer.bank
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public void setBank(String bank) {
        this.bank = bank == null ? null : bank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.bank_account
     *
     * @return the value of t_customer.bank_account
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public String getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.bank_account
     *
     * @param bankAccount the value for t_customer.bank_account
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount == null ? null : bankAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.phone
     *
     * @return the value of t_customer.phone
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.phone
     *
     * @param phone the value for t_customer.phone
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }
}