package com.xt.edu.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public OrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_order
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andWebcourseIdIsNull() {
            addCriterion("webcourse_id is null");
            return (Criteria) this;
        }

        public Criteria andWebcourseIdIsNotNull() {
            addCriterion("webcourse_id is not null");
            return (Criteria) this;
        }

        public Criteria andWebcourseIdEqualTo(String value) {
            addCriterion("webcourse_id =", value, "webcourseId");
            return (Criteria) this;
        }

        public Criteria andWebcourseIdNotEqualTo(String value) {
            addCriterion("webcourse_id <>", value, "webcourseId");
            return (Criteria) this;
        }

        public Criteria andWebcourseIdGreaterThan(String value) {
            addCriterion("webcourse_id >", value, "webcourseId");
            return (Criteria) this;
        }

        public Criteria andWebcourseIdGreaterThanOrEqualTo(String value) {
            addCriterion("webcourse_id >=", value, "webcourseId");
            return (Criteria) this;
        }

        public Criteria andWebcourseIdLessThan(String value) {
            addCriterion("webcourse_id <", value, "webcourseId");
            return (Criteria) this;
        }

        public Criteria andWebcourseIdLessThanOrEqualTo(String value) {
            addCriterion("webcourse_id <=", value, "webcourseId");
            return (Criteria) this;
        }

        public Criteria andWebcourseIdLike(String value) {
            addCriterion("webcourse_id like", value, "webcourseId");
            return (Criteria) this;
        }

        public Criteria andWebcourseIdNotLike(String value) {
            addCriterion("webcourse_id not like", value, "webcourseId");
            return (Criteria) this;
        }

        public Criteria andWebcourseIdIn(List<String> values) {
            addCriterion("webcourse_id in", values, "webcourseId");
            return (Criteria) this;
        }

        public Criteria andWebcourseIdNotIn(List<String> values) {
            addCriterion("webcourse_id not in", values, "webcourseId");
            return (Criteria) this;
        }

        public Criteria andWebcourseIdBetween(String value1, String value2) {
            addCriterion("webcourse_id between", value1, value2, "webcourseId");
            return (Criteria) this;
        }

        public Criteria andWebcourseIdNotBetween(String value1, String value2) {
            addCriterion("webcourse_id not between", value1, value2, "webcourseId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andPaystateIsNull() {
            addCriterion("paystate is null");
            return (Criteria) this;
        }

        public Criteria andPaystateIsNotNull() {
            addCriterion("paystate is not null");
            return (Criteria) this;
        }

        public Criteria andPaystateEqualTo(String value) {
            addCriterion("paystate =", value, "paystate");
            return (Criteria) this;
        }

        public Criteria andPaystateNotEqualTo(String value) {
            addCriterion("paystate <>", value, "paystate");
            return (Criteria) this;
        }

        public Criteria andPaystateGreaterThan(String value) {
            addCriterion("paystate >", value, "paystate");
            return (Criteria) this;
        }

        public Criteria andPaystateGreaterThanOrEqualTo(String value) {
            addCriterion("paystate >=", value, "paystate");
            return (Criteria) this;
        }

        public Criteria andPaystateLessThan(String value) {
            addCriterion("paystate <", value, "paystate");
            return (Criteria) this;
        }

        public Criteria andPaystateLessThanOrEqualTo(String value) {
            addCriterion("paystate <=", value, "paystate");
            return (Criteria) this;
        }

        public Criteria andPaystateLike(String value) {
            addCriterion("paystate like", value, "paystate");
            return (Criteria) this;
        }

        public Criteria andPaystateNotLike(String value) {
            addCriterion("paystate not like", value, "paystate");
            return (Criteria) this;
        }

        public Criteria andPaystateIn(List<String> values) {
            addCriterion("paystate in", values, "paystate");
            return (Criteria) this;
        }

        public Criteria andPaystateNotIn(List<String> values) {
            addCriterion("paystate not in", values, "paystate");
            return (Criteria) this;
        }

        public Criteria andPaystateBetween(String value1, String value2) {
            addCriterion("paystate between", value1, value2, "paystate");
            return (Criteria) this;
        }

        public Criteria andPaystateNotBetween(String value1, String value2) {
            addCriterion("paystate not between", value1, value2, "paystate");
            return (Criteria) this;
        }

        public Criteria andAmountIsNull() {
            addCriterion("amount is null");
            return (Criteria) this;
        }

        public Criteria andAmountIsNotNull() {
            addCriterion("amount is not null");
            return (Criteria) this;
        }

        public Criteria andAmountEqualTo(Long value) {
            addCriterion("amount =", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotEqualTo(Long value) {
            addCriterion("amount <>", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThan(Long value) {
            addCriterion("amount >", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("amount >=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThan(Long value) {
            addCriterion("amount <", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThanOrEqualTo(Long value) {
            addCriterion("amount <=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountIn(List<Long> values) {
            addCriterion("amount in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotIn(List<Long> values) {
            addCriterion("amount not in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountBetween(Long value1, Long value2) {
            addCriterion("amount between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotBetween(Long value1, Long value2) {
            addCriterion("amount not between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andStudentIdIsNull() {
            addCriterion("student_id is null");
            return (Criteria) this;
        }

        public Criteria andStudentIdIsNotNull() {
            addCriterion("student_id is not null");
            return (Criteria) this;
        }

        public Criteria andStudentIdEqualTo(String value) {
            addCriterion("student_id =", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotEqualTo(String value) {
            addCriterion("student_id <>", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThan(String value) {
            addCriterion("student_id >", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThanOrEqualTo(String value) {
            addCriterion("student_id >=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThan(String value) {
            addCriterion("student_id <", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThanOrEqualTo(String value) {
            addCriterion("student_id <=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLike(String value) {
            addCriterion("student_id like", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotLike(String value) {
            addCriterion("student_id not like", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdIn(List<String> values) {
            addCriterion("student_id in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotIn(List<String> values) {
            addCriterion("student_id not in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdBetween(String value1, String value2) {
            addCriterion("student_id between", value1, value2, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotBetween(String value1, String value2) {
            addCriterion("student_id not between", value1, value2, "studentId");
            return (Criteria) this;
        }

        public Criteria andRecieverNameIsNull() {
            addCriterion("reciever_name is null");
            return (Criteria) this;
        }

        public Criteria andRecieverNameIsNotNull() {
            addCriterion("reciever_name is not null");
            return (Criteria) this;
        }

        public Criteria andRecieverNameEqualTo(String value) {
            addCriterion("reciever_name =", value, "recieverName");
            return (Criteria) this;
        }

        public Criteria andRecieverNameNotEqualTo(String value) {
            addCriterion("reciever_name <>", value, "recieverName");
            return (Criteria) this;
        }

        public Criteria andRecieverNameGreaterThan(String value) {
            addCriterion("reciever_name >", value, "recieverName");
            return (Criteria) this;
        }

        public Criteria andRecieverNameGreaterThanOrEqualTo(String value) {
            addCriterion("reciever_name >=", value, "recieverName");
            return (Criteria) this;
        }

        public Criteria andRecieverNameLessThan(String value) {
            addCriterion("reciever_name <", value, "recieverName");
            return (Criteria) this;
        }

        public Criteria andRecieverNameLessThanOrEqualTo(String value) {
            addCriterion("reciever_name <=", value, "recieverName");
            return (Criteria) this;
        }

        public Criteria andRecieverNameLike(String value) {
            addCriterion("reciever_name like", value, "recieverName");
            return (Criteria) this;
        }

        public Criteria andRecieverNameNotLike(String value) {
            addCriterion("reciever_name not like", value, "recieverName");
            return (Criteria) this;
        }

        public Criteria andRecieverNameIn(List<String> values) {
            addCriterion("reciever_name in", values, "recieverName");
            return (Criteria) this;
        }

        public Criteria andRecieverNameNotIn(List<String> values) {
            addCriterion("reciever_name not in", values, "recieverName");
            return (Criteria) this;
        }

        public Criteria andRecieverNameBetween(String value1, String value2) {
            addCriterion("reciever_name between", value1, value2, "recieverName");
            return (Criteria) this;
        }

        public Criteria andRecieverNameNotBetween(String value1, String value2) {
            addCriterion("reciever_name not between", value1, value2, "recieverName");
            return (Criteria) this;
        }

        public Criteria andRecieverAddressIsNull() {
            addCriterion("reciever_address is null");
            return (Criteria) this;
        }

        public Criteria andRecieverAddressIsNotNull() {
            addCriterion("reciever_address is not null");
            return (Criteria) this;
        }

        public Criteria andRecieverAddressEqualTo(String value) {
            addCriterion("reciever_address =", value, "recieverAddress");
            return (Criteria) this;
        }

        public Criteria andRecieverAddressNotEqualTo(String value) {
            addCriterion("reciever_address <>", value, "recieverAddress");
            return (Criteria) this;
        }

        public Criteria andRecieverAddressGreaterThan(String value) {
            addCriterion("reciever_address >", value, "recieverAddress");
            return (Criteria) this;
        }

        public Criteria andRecieverAddressGreaterThanOrEqualTo(String value) {
            addCriterion("reciever_address >=", value, "recieverAddress");
            return (Criteria) this;
        }

        public Criteria andRecieverAddressLessThan(String value) {
            addCriterion("reciever_address <", value, "recieverAddress");
            return (Criteria) this;
        }

        public Criteria andRecieverAddressLessThanOrEqualTo(String value) {
            addCriterion("reciever_address <=", value, "recieverAddress");
            return (Criteria) this;
        }

        public Criteria andRecieverAddressLike(String value) {
            addCriterion("reciever_address like", value, "recieverAddress");
            return (Criteria) this;
        }

        public Criteria andRecieverAddressNotLike(String value) {
            addCriterion("reciever_address not like", value, "recieverAddress");
            return (Criteria) this;
        }

        public Criteria andRecieverAddressIn(List<String> values) {
            addCriterion("reciever_address in", values, "recieverAddress");
            return (Criteria) this;
        }

        public Criteria andRecieverAddressNotIn(List<String> values) {
            addCriterion("reciever_address not in", values, "recieverAddress");
            return (Criteria) this;
        }

        public Criteria andRecieverAddressBetween(String value1, String value2) {
            addCriterion("reciever_address between", value1, value2, "recieverAddress");
            return (Criteria) this;
        }

        public Criteria andRecieverAddressNotBetween(String value1, String value2) {
            addCriterion("reciever_address not between", value1, value2, "recieverAddress");
            return (Criteria) this;
        }

        public Criteria andRecieverPhoneIsNull() {
            addCriterion("reciever_phone is null");
            return (Criteria) this;
        }

        public Criteria andRecieverPhoneIsNotNull() {
            addCriterion("reciever_phone is not null");
            return (Criteria) this;
        }

        public Criteria andRecieverPhoneEqualTo(String value) {
            addCriterion("reciever_phone =", value, "recieverPhone");
            return (Criteria) this;
        }

        public Criteria andRecieverPhoneNotEqualTo(String value) {
            addCriterion("reciever_phone <>", value, "recieverPhone");
            return (Criteria) this;
        }

        public Criteria andRecieverPhoneGreaterThan(String value) {
            addCriterion("reciever_phone >", value, "recieverPhone");
            return (Criteria) this;
        }

        public Criteria andRecieverPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("reciever_phone >=", value, "recieverPhone");
            return (Criteria) this;
        }

        public Criteria andRecieverPhoneLessThan(String value) {
            addCriterion("reciever_phone <", value, "recieverPhone");
            return (Criteria) this;
        }

        public Criteria andRecieverPhoneLessThanOrEqualTo(String value) {
            addCriterion("reciever_phone <=", value, "recieverPhone");
            return (Criteria) this;
        }

        public Criteria andRecieverPhoneLike(String value) {
            addCriterion("reciever_phone like", value, "recieverPhone");
            return (Criteria) this;
        }

        public Criteria andRecieverPhoneNotLike(String value) {
            addCriterion("reciever_phone not like", value, "recieverPhone");
            return (Criteria) this;
        }

        public Criteria andRecieverPhoneIn(List<String> values) {
            addCriterion("reciever_phone in", values, "recieverPhone");
            return (Criteria) this;
        }

        public Criteria andRecieverPhoneNotIn(List<String> values) {
            addCriterion("reciever_phone not in", values, "recieverPhone");
            return (Criteria) this;
        }

        public Criteria andRecieverPhoneBetween(String value1, String value2) {
            addCriterion("reciever_phone between", value1, value2, "recieverPhone");
            return (Criteria) this;
        }

        public Criteria andRecieverPhoneNotBetween(String value1, String value2) {
            addCriterion("reciever_phone not between", value1, value2, "recieverPhone");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_order
     *
     * @mbg.generated do_not_delete_during_merge Thu Jan 17 19:49:31 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_order
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}