package com.xt.edu.model;

import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.id
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.webcourse_id
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    private String webcourseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.create_time
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.paystate
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    private String paystate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.amount
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    private Long amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.student_id
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    private String studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.reciever_name
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    private String recieverName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.reciever_address
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    private String recieverAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.reciever_phone
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    private String recieverPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.id
     *
     * @return the value of t_order.id
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.id
     *
     * @param id the value for t_order.id
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.webcourse_id
     *
     * @return the value of t_order.webcourse_id
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public String getWebcourseId() {
        return webcourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.webcourse_id
     *
     * @param webcourseId the value for t_order.webcourse_id
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public void setWebcourseId(String webcourseId) {
        this.webcourseId = webcourseId == null ? null : webcourseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.create_time
     *
     * @return the value of t_order.create_time
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.create_time
     *
     * @param createTime the value for t_order.create_time
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.paystate
     *
     * @return the value of t_order.paystate
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public String getPaystate() {
        return paystate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.paystate
     *
     * @param paystate the value for t_order.paystate
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public void setPaystate(String paystate) {
        this.paystate = paystate == null ? null : paystate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.amount
     *
     * @return the value of t_order.amount
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.amount
     *
     * @param amount the value for t_order.amount
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.student_id
     *
     * @return the value of t_order.student_id
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.student_id
     *
     * @param studentId the value for t_order.student_id
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.reciever_name
     *
     * @return the value of t_order.reciever_name
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public String getRecieverName() {
        return recieverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.reciever_name
     *
     * @param recieverName the value for t_order.reciever_name
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public void setRecieverName(String recieverName) {
        this.recieverName = recieverName == null ? null : recieverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.reciever_address
     *
     * @return the value of t_order.reciever_address
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public String getRecieverAddress() {
        return recieverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.reciever_address
     *
     * @param recieverAddress the value for t_order.reciever_address
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public void setRecieverAddress(String recieverAddress) {
        this.recieverAddress = recieverAddress == null ? null : recieverAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.reciever_phone
     *
     * @return the value of t_order.reciever_phone
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public String getRecieverPhone() {
        return recieverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.reciever_phone
     *
     * @param recieverPhone the value for t_order.reciever_phone
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public void setRecieverPhone(String recieverPhone) {
        this.recieverPhone = recieverPhone == null ? null : recieverPhone.trim();
    }
}