package com.xt.edu.model;

public class Recommend {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recommend.id
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recommend.student_id
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    private String studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recommend.course_id
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recommend.referrer_id
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    private Integer referrerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recommend.commission
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    private Long commission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recommend.paystate
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    private String paystate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recommend.id
     *
     * @return the value of t_recommend.id
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recommend.id
     *
     * @param id the value for t_recommend.id
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recommend.student_id
     *
     * @return the value of t_recommend.student_id
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recommend.student_id
     *
     * @param studentId the value for t_recommend.student_id
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recommend.course_id
     *
     * @return the value of t_recommend.course_id
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recommend.course_id
     *
     * @param courseId the value for t_recommend.course_id
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recommend.referrer_id
     *
     * @return the value of t_recommend.referrer_id
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public Integer getReferrerId() {
        return referrerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recommend.referrer_id
     *
     * @param referrerId the value for t_recommend.referrer_id
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public void setReferrerId(Integer referrerId) {
        this.referrerId = referrerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recommend.commission
     *
     * @return the value of t_recommend.commission
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public Long getCommission() {
        return commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recommend.commission
     *
     * @param commission the value for t_recommend.commission
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public void setCommission(Long commission) {
        this.commission = commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recommend.paystate
     *
     * @return the value of t_recommend.paystate
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public String getPaystate() {
        return paystate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recommend.paystate
     *
     * @param paystate the value for t_recommend.paystate
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public void setPaystate(String paystate) {
        this.paystate = paystate == null ? null : paystate.trim();
    }
}