package com.xt.edu.model;

import java.util.Date;

public class Royalty {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_royalty.id
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_royalty.customer
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    private Integer customer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_royalty.total_salary
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    private Long totalSalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_royalty.settling_month
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    private String settlingMonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_royalty.paystate
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    private String paystate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_royalty.arrive_time
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    private Date arriveTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_royalty.need_invoice
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    private String needInvoice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_royalty.tax
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    private Long tax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_royalty.invoice_address
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    private String invoiceAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_royalty.id
     *
     * @return the value of t_royalty.id
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_royalty.id
     *
     * @param id the value for t_royalty.id
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_royalty.customer
     *
     * @return the value of t_royalty.customer
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public Integer getCustomer() {
        return customer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_royalty.customer
     *
     * @param customer the value for t_royalty.customer
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public void setCustomer(Integer customer) {
        this.customer = customer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_royalty.total_salary
     *
     * @return the value of t_royalty.total_salary
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public Long getTotalSalary() {
        return totalSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_royalty.total_salary
     *
     * @param totalSalary the value for t_royalty.total_salary
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public void setTotalSalary(Long totalSalary) {
        this.totalSalary = totalSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_royalty.settling_month
     *
     * @return the value of t_royalty.settling_month
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public String getSettlingMonth() {
        return settlingMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_royalty.settling_month
     *
     * @param settlingMonth the value for t_royalty.settling_month
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public void setSettlingMonth(String settlingMonth) {
        this.settlingMonth = settlingMonth == null ? null : settlingMonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_royalty.paystate
     *
     * @return the value of t_royalty.paystate
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public String getPaystate() {
        return paystate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_royalty.paystate
     *
     * @param paystate the value for t_royalty.paystate
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public void setPaystate(String paystate) {
        this.paystate = paystate == null ? null : paystate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_royalty.arrive_time
     *
     * @return the value of t_royalty.arrive_time
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public Date getArriveTime() {
        return arriveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_royalty.arrive_time
     *
     * @param arriveTime the value for t_royalty.arrive_time
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public void setArriveTime(Date arriveTime) {
        this.arriveTime = arriveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_royalty.need_invoice
     *
     * @return the value of t_royalty.need_invoice
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public String getNeedInvoice() {
        return needInvoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_royalty.need_invoice
     *
     * @param needInvoice the value for t_royalty.need_invoice
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public void setNeedInvoice(String needInvoice) {
        this.needInvoice = needInvoice == null ? null : needInvoice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_royalty.tax
     *
     * @return the value of t_royalty.tax
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public Long getTax() {
        return tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_royalty.tax
     *
     * @param tax the value for t_royalty.tax
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public void setTax(Long tax) {
        this.tax = tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_royalty.invoice_address
     *
     * @return the value of t_royalty.invoice_address
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public String getInvoiceAddress() {
        return invoiceAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_royalty.invoice_address
     *
     * @param invoiceAddress the value for t_royalty.invoice_address
     *
     * @mbg.generated Thu Jan 17 19:49:31 CST 2019
     */
    public void setInvoiceAddress(String invoiceAddress) {
        this.invoiceAddress = invoiceAddress == null ? null : invoiceAddress.trim();
    }
}